#!/bin/bash
#
# nat-monitor    This shell script takes care of starting and stopping
#   nat-monitor.
#
# chkconfig: - 58 74
# description: nat-monitor\
# Takes care of monitoring the partner NAT Instance to ensure it is up. \
# Handles failover if the other instance is down, and tries to reboot it to \
# get it up and running again.

### BEGIN INIT INFO
# Provides: nat-monitoring
# Required-Start: $network $local_fs $remote_fs
# Required-Stop: $network $local_fs $remote_fs
# Should-Start: $syslog $named
# Should-Stop: $syslog $named
# Short-Description: start and stop nat-monitor
### END INIT INFO

# Source function library.
. /etc/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

prog=nat-monitor
lockfile=/var/lock/subsys/$prog

start() {

  # Start daemon.
  echo -n $"Starting $prog: "
  /usr/bin/nat-monitor >> /tmp/nat-monitor.log &
  # daemon $prog -p /var/run/$prog.pid
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch $lockfile
  return $RETVAL
}

stop() {
  [ "$EUID" != "0" ] && exit 4
        echo -n $"Shutting down $prog: "
  killproc $prog
  RETVAL=$?
        echo
  [ $RETVAL -eq 0 ] && rm -f $lockfile
  return $RETVAL
}

# See how we were called.
case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  status)
  status $prog
  ;;
  restart|force-reload)
  stop
  start
  ;;
  try-restart|condrestart)
  if status $prog > /dev/null; then
      stop
      start
  fi
  ;;
  reload)
  exit 3
  ;;
  *)
  echo $"Usage: $0 {start|stop|status|restart|try-restart|force-reload}"
  exit 2
esac