- name: Configure nat_monitoring for routing failover
  hosts: nat_instances
  gather_facts: False
  sudo: True
  tasks:
    - name: copy nat_monitor script to /usr/bin
      template: >
        src=templates/nat-monitor.j2
        dest=/usr/bin/nat-monitor
        mode=0700

    - name: copy nat_monitor init script
      copy: > 
        src=files/nat-monitor 
        dest=/etc/init.d/nat-monitor 
        ower=root 
        group=root 
        mode=0755

    - name: create NAT monitor log
      file: > 
        path=/tmp/nat-monitor.log 
        state=touch 
        owner=root 
        group=root 
        mode=0644

    - name: enable nat-monitor service
      service: name=nat-monitor enabled=yes

    - name: start nat-monitor service
      service: name=nat-monitor state=started
